### ISSUE TITLE
conflict with automatic redirect tool

### ISSUE THREAD

**Issue by peterjacobs** [collective/collective.redirectacquired#2]
Plone keeps track of which files/folders have been moved and automatically redirects to the new location.

In some cases collective.redirectacquired does not take this rewrite in account.

example:
create a structure:
```
dir1-> dir2 -> page1
dir2
```
Then rename "dir1 -> dir2" to "dir1 -> dir3"
```
dir1-> dir3 -> page1
dir2
```
the url http://domain/dir1/dir2/page1 wil point to http://domain/dir1/dir3/page1 

but the output of  collective.redirectacquired will be:

> INFO redirect.acquired redirect from 'http://domain/dir1/dir2/page1' to CANONICAL_URL 'http://domain/dir2/page1'

The result is a redirect to a non-existent page.

Possible solution: don't redirect when the result of the original request would be "301 Moved Permanently" generated by the Plone redirect tool

**Comment by gotcha** [comment]
Fixed in  cb5ddf3

**Comment by gotcha** [comment]
> create a structure:
> ```
> dir1-> dir2 -> page1
> dir2
> ```
> Then rename "dir1 -> dir2" to "dir1 -> dir3"
> ```
> dir1-> dir3 -> page1
> dir2
> ```

The implementation in  cb5ddf3 raises an exception instead of letting normal flow happen to cover for the case where `dir2` would also hold a `page1`.

In that case, `http://domain/dir1/dir2/page1` would resolve to `http://domain/dir2/page1` when `collective.redirectacquired` kicks in even though there is a very high probability that it is actually a remnant of the previous content history and it should use the redirector knowledge IOW redirect to `http://domain/dir1/dir3/page1`.

**Comment by gotcha** [comment]
Refactoring made for https://github.com/collective/collective.redirectacquired/issues/3 made cb5ddf3 useless.
